### ISSUE TITLE
Laest Update Broke Plugin

### ISSUE THREAD

**Issue by ArcTheWolf** [MidoriKami/CurrencyAlert#17]
The latest update that was rolled out has rendered Currency Alert unusable. It says it requires UI Resolution to be set to "High (WQHD/4K)" when it previously did not requires this. But when you set your System Config setting to the required setting and restart it still does not work and says "UI Resolution" System Configuration setting needs to be set to "High (WQHD/4K)" Plugin was working just fine today until this update came out.

**Comment by MidoriKami** [comment]
Requires this setting in the System Configuration option to be set.

The plugin will not load if this setting is not set to the shown value. This is intentional behavior.

After changing to this setting a game restart is required.

![image](https://github.com/user-attachments/assets/b10dab54-b1c7-4998-977f-e54b530eb749)

**Comment by ArcTheWolf** [comment]
Ohhhhh I was changing the wrong resolution. My bad thanks for the quick response :)
